language: python

python:
  - 3.6.4

install:
  - pip install -r requirements.txt

script:
  - flake8 .
  - pytest -s -x

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

notifications:
  email: false

